/**
 * i18n — t() function + locale helpers.
 *
 * SSOT: locales/ssot.json  →  data.ts (generated by scripts/compile-locales.ts)
 *
 * Usage (client):
 *   import { t } from '@authentik/utils';
 *   t('browse.search.placeholder')            // → "搜尋品牌、型號、關鍵字…"
 *   t('browse.search.placeholder', {}, 'en')  // → "Search brands, models, keywords…"
 *   t('browse.filter.viewResults', { count: 12 })  // → "查看 12 件結果"
 *
 * Usage (server component):
 *   import { getLocale } from '@authentik/utils';
 *   import { headers } from 'next/headers';
 *   const locale = getLocale(headers());  // reads x-locale header
 */

import { zhMap, enMap, type TLocale, type TKey, DEFAULT_LOCALE } from './data';

// ─── Core t() ────────────────────────────────────────────────────────────────

/**
 * Translate a key into the given locale, interpolating {placeholder} values.
 *
 * @param key    Dot-notation key (e.g. "browse.search.placeholder")
 * @param params Optional object of {variable: value} to interpolate
 * @param locale "zh" (default) or "en"
 * @returns      Translated string, or the key itself if not found
 */
export function t(key: string, params?: Record<string, string | number>, locale?: TLocale): string {
  const map = locale === 'en' ? enMap : zhMap;
  let str = map[key];
  if (str === undefined) {
    // Fallback to zh, then to the key itself
    str = zhMap[key] ?? key;
  }
  if (!params) return str;
  return str.replace(/\{([\w.]+)\}/g, (_, name) => {
    const val = params[name];
    return val !== undefined ? String(val) : `{${name}}`;
  });
}

/**
 * Create a locale-aware t() function.
 * @example
 *   const _t = createT(locale);
 *   _t('browse.search.placeholder') // → "搜尋…" or "Search…"
 */
export function createT(locale: TLocale) {
  return (key: string, params?: Record<string, string | number>) => t(key, params, locale);
}

// ─── Locale detection ────────────────────────────────────────────────────────

/**
 * Detect locale from cookie.
 * Works on both client (document.cookie) and server (cookies() from next/headers).
 */
export function detectLocale(cookie?: string | null): TLocale {
  if (!cookie) return DEFAULT_LOCALE;
  const m = cookie.match(/(?:^|;\s*)lang=(\w+)/);
  if (m && (m[1] === 'en' || m[1] === 'zh')) return m[1] as TLocale;
  return DEFAULT_LOCALE;
}

/**
 * Get locale from Next.js headers object (server components).
 * Pass the result of `headers()` or `cookies()`.
 */
export function getLocaleFromCookieStr(cookieStr: string | null | undefined): TLocale {
  return detectLocale(cookieStr);
}

/**
 * Client-side locale read from document.cookie.
 * Falls back to DEFAULT_LOCALE if no cookie or SSR.
 */
export function getClientLocale(): TLocale {
  if (typeof document === 'undefined') return DEFAULT_LOCALE;
  return detectLocale(document.cookie);
}

// ─── Locale switching ────────────────────────────────────────────────────────

/**
 * Set locale and reload. Call from a language-switcher UI.
 */
export function setLocale(locale: TLocale): void {
  if (typeof document === 'undefined') return;
  document.cookie = `lang=${locale}; path=/; max-age=${365 * 24 * 60 * 60}; SameSite=Lax`;
  window.location.reload();
}

// ─── Re-export types ─────────────────────────────────────────────────────────

export type { TLocale, TKey } from './data';
export { zhMap, enMap, DEFAULT_LOCALE } from './data';
